USE defaultdb;
TRUNCATE TABLE state_names;
TRUNCATE TABLE crop_names;
INSERT INTO state_names (state_name) VALUES ('Andhra Pradesh');
INSERT INTO state_names (state_name) VALUES ('Arunachal Pradesh');
INSERT INTO state_names (state_name) VALUES ('Assam');
INSERT INTO state_names (state_name) VALUES ('Bihar');
INSERT INTO state_names (state_name) VALUES ('Chhattisgarh');
INSERT INTO state_names (state_name) VALUES ('Delhi');
INSERT INTO state_names (state_name) VALUES ('Goa');
INSERT INTO state_names (state_name) VALUES ('Gujarat');
INSERT INTO state_names (state_name) VALUES ('Haryana');
INSERT INTO state_names (state_name) VALUES ('Himachal Pradesh');
INSERT INTO state_names (state_name) VALUES ('Jammu and Kashmir');
INSERT INTO state_names (state_name) VALUES ('Jharkhand');
INSERT INTO state_names (state_name) VALUES ('Karnataka');
INSERT INTO state_names (state_name) VALUES ('Kerala');
INSERT INTO state_names (state_name) VALUES ('Madhya Pradesh');
INSERT INTO state_names (state_name) VALUES ('Maharashtra');
INSERT INTO state_names (state_name) VALUES ('Manipur');
INSERT INTO state_names (state_name) VALUES ('Meghalaya');
INSERT INTO state_names (state_name) VALUES ('Mizoram');
INSERT INTO state_names (state_name) VALUES ('Nagaland');
INSERT INTO state_names (state_name) VALUES ('Odisha');
INSERT INTO state_names (state_name) VALUES ('Puducherry');
INSERT INTO state_names (state_name) VALUES ('Punjab');
INSERT INTO state_names (state_name) VALUES ('Sikkim');
INSERT INTO state_names (state_name) VALUES ('Tamil Nadu');
INSERT INTO state_names (state_name) VALUES ('Telangana');
INSERT INTO state_names (state_name) VALUES ('Tripura');
INSERT INTO state_names (state_name) VALUES ('Uttar Pradesh');
INSERT INTO state_names (state_name) VALUES ('Uttarakhand');
INSERT INTO state_names (state_name) VALUES ('West Bengal');
INSERT INTO crop_names (crop_name) VALUES ('Arecanut');
INSERT INTO crop_names (crop_name) VALUES ('Arhar/Tur');
INSERT INTO crop_names (crop_name) VALUES ('Bajra');
INSERT INTO crop_names (crop_name) VALUES ('Banana');
INSERT INTO crop_names (crop_name) VALUES ('Barley');
INSERT INTO crop_names (crop_name) VALUES ('Black pepper');
INSERT INTO crop_names (crop_name) VALUES ('Cardamom');
INSERT INTO crop_names (crop_name) VALUES ('Cashewnut');
INSERT INTO crop_names (crop_name) VALUES ('Castor seed');
INSERT INTO crop_names (crop_name) VALUES ('Coconut');
INSERT INTO crop_names (crop_name) VALUES ('Coriander');
INSERT INTO crop_names (crop_name) VALUES ('Cotton(lint)');
INSERT INTO crop_names (crop_name) VALUES ('Cowpea(Lobia)');
INSERT INTO crop_names (crop_name) VALUES ('Dry chillies');
INSERT INTO crop_names (crop_name) VALUES ('Garlic');
INSERT INTO crop_names (crop_name) VALUES ('Ginger');
INSERT INTO crop_names (crop_name) VALUES ('Gram');
INSERT INTO crop_names (crop_name) VALUES ('Groundnut');
INSERT INTO crop_names (crop_name) VALUES ('Guar seed');
INSERT INTO crop_names (crop_name) VALUES ('Horse-gram');
INSERT INTO crop_names (crop_name) VALUES ('Jowar');
INSERT INTO crop_names (crop_name) VALUES ('Jute');
INSERT INTO crop_names (crop_name) VALUES ('Khesari');
INSERT INTO crop_names (crop_name) VALUES ('Linseed');
INSERT INTO crop_names (crop_name) VALUES ('Maize');
INSERT INTO crop_names (crop_name) VALUES ('Masoor');
INSERT INTO crop_names (crop_name) VALUES ('Mesta');
INSERT INTO crop_names (crop_name) VALUES ('Moong(Green Gram)');
INSERT INTO crop_names (crop_name) VALUES ('Moth');
INSERT INTO crop_names (crop_name) VALUES ('Niger seed');
INSERT INTO crop_names (crop_name) VALUES ('Oilseeds total');
INSERT INTO crop_names (crop_name) VALUES ('Onion');
INSERT INTO crop_names (crop_name) VALUES ('Other  Rabi pulses');
INSERT INTO crop_names (crop_name) VALUES ('Other Cereals');
INSERT INTO crop_names (crop_name) VALUES ('Other Kharif pulses');
INSERT INTO crop_names (crop_name) VALUES ('Other Summer Pulses');
INSERT INTO crop_names (crop_name) VALUES ('Peas & beans (Pulses)');
INSERT INTO crop_names (crop_name) VALUES ('Potato');
INSERT INTO crop_names (crop_name) VALUES ('Ragi');
INSERT INTO crop_names (crop_name) VALUES ('Rapeseed &Mustard');
INSERT INTO crop_names (crop_name) VALUES ('Rice');
INSERT INTO crop_names (crop_name) VALUES ('Safflower');
INSERT INTO crop_names (crop_name) VALUES ('Sannhamp');
INSERT INTO crop_names (crop_name) VALUES ('Sesamum');
INSERT INTO crop_names (crop_name) VALUES ('Small millets');
INSERT INTO crop_names (crop_name) VALUES ('Soyabean');
INSERT INTO crop_names (crop_name) VALUES ('Sugarcane');
INSERT INTO crop_names (crop_name) VALUES ('Sunflower');
INSERT INTO crop_names (crop_name) VALUES ('Sweet potato');
INSERT INTO crop_names (crop_name) VALUES ('Tapioca');
INSERT INTO crop_names (crop_name) VALUES ('Tobacco');
INSERT INTO crop_names (crop_name) VALUES ('Turmeric');
INSERT INTO crop_names (crop_name) VALUES ('Urad');
INSERT INTO crop_names (crop_name) VALUES ('Wheat');
INSERT INTO crop_names (crop_name) VALUES ('other oilseeds');