spring.application.name=Yield_Prediction
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/YieldData}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:my-secret-pw}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# FastAPI ML Model API
fastapi.url=${FASTAPI_URL:http://localhost:8000}